<<<<<<< HEAD
﻿name: Deno CI/CD
=======
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

>>>>>>> 88538b7c43be5918a9225daba119802917a5bc41
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
<<<<<<< HEAD
  deployments: write
=======
>>>>>>> 88538b7c43be5918a9225daba119802917a5bc41

jobs:
  test:
    runs-on: ubuntu-latest
<<<<<<< HEAD
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.x"
      - run: deno lint
      - run: deno test -A

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == "refs/heads/main"
    steps:
      - run: echo "Deno Deploy will auto-deploy if connected"
=======

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A
>>>>>>> 88538b7c43be5918a9225daba119802917a5bc41
